sudo: required

services:
  - docker

before_install:
  - cd frontend
  - docker build -t kkulewski/frontend -f ./frontend/Dockerfile.dev ./frontend

before_script:
  - cd frontend

script:
  - docker run -e CI=true kkulewski/frontend yarn test
