sudo: required

services:
  - docker

before_install:
  - docker build -t kkulewski/backend -f ./lab-06/backend/Dockerfile.dev ./lab-06/backend
  - docker build -t kkulewski/frontend -f ./lab-06/frontend/Dockerfile.dev ./lab-06/frontend

script:
  - docker run -e CI=true kkulewski/frontend yarn test
