version: '3'

services:
  my-postgres:
    image: 'postgres:latest'
    container_name: my-postgres
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}

  my-redis:
    image: 'redis:latest'
    container_name: my-redis

  my-backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: my-backend
    volumes:
      - /opt/app/node_modules
      - ./backend:/opt/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    ports:
      - '5000:5000'

  my-frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: my-frontend
    volumes:
      - /opt/app/node_modules
      - ./frontend:/opt/app
    tty: true
    ports:
      - '4000:3000'

  my-nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    container_name: my-nginx
    ports:
      - '8080:80'

