version: '3'

services:
  my-postgres-server:
    image: 'postgres:atest'
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}

  my-redis-server:
    image: 'redis:latest'

  my-backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /opt/app/node_modules
      - ./backend:/opt/app
    ports:
      - '5000:5000'
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}

