apiVersion: apps/v1

kind: Deployment

metadata:
  name: my-backend-deployment
  labels:
    app: my-backend
    type: backend

spec:
  template:
    metadata:
      name: my-backend-pod
      labels:
        app: my-backend
        type: backend
    spec:
      containers:
        - name: my-backend-container
          image: kkulewski/mybackend
          envFrom:
            - configMapRef:
                name: my-app-configmap
            - secretRef:
                name: my-postgres-secret
  replicas: 3
  selector:
    matchLabels:
      app: my-backend
      type: backend
